// generated by ginger from go generate -- DO NOT EDIT
package main

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"github.com/jinzhu/gorm"
	"log"
	"net/http"
	"strconv"
	"time"
)


type TaipeiCityResource struct {
	db gorm.DB
}

// @Title CreateTaipeiCity
// @Description get string by ID
// @Accept  json
// @Param   some_id     path    int     true        "Some ID"
// @Success 201 {object} string
// @Failure 400 {object} APIError "problem decoding body"
// @Router /taipeiCity/ [post]
func (tr *TaipeiCityResource) CreateTaipeiCity(c *gin.Context) {
	var taipeiCity TaipeiCity

	if c.Bind(&taipeiCity) != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem decoding body"})
		return
	}
	//taipeiCity.Status = TaipeiCityStatus
	taipeiCity.Ginger_Created = int32(time.Now().Unix())

	tr.db.Save(&taipeiCity)

	c.JSON(http.StatusCreated, taipeiCity)
}

func (tr *TaipeiCityResource) GetAllTaipeiCitys(c *gin.Context) {
	var taipeiCitys []TaipeiCity

	tr.db.Order("ginger__created desc").Find(&taipeiCitys)

	c.JSON(http.StatusOK, taipeiCitys)
}

func (tr *TaipeiCityResource) GetTaipeiCity(c *gin.Context) {
	id, err := tr.getId(c)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem decoding id sent"})
		return
	}

	var taipeiCity TaipeiCity

	if tr.db.First(&taipeiCity, id).RecordNotFound() {
		c.JSON(http.StatusNotFound, gin.H{"message": "not found"})
	} else {
		c.JSON(http.StatusOK, taipeiCity)
	}
}

func (tr *TaipeiCityResource) UpdateTaipeiCity(c *gin.Context) {
	id, err := tr.getId(c)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem decoding id sent"})
		return
	}

	var taipeiCity TaipeiCity

	if c.Bind(&taipeiCity) != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem decoding body"})
		return
	}
	taipeiCity.Ginger_Id = int32(id)

	var existing TaipeiCity

	if tr.db.First(&existing, id).RecordNotFound() {
		c.JSON(http.StatusNotFound, gin.H{"message": "not found"})
	} else {
		tr.db.Save(&taipeiCity)
		c.JSON(http.StatusOK, taipeiCity)
	}

}

func (tr *TaipeiCityResource) PatchTaipeiCity(c *gin.Context) {
	id, err := tr.getId(c)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem decoding id sent"})
		return
	}

	// this is a hack because Gin falsely claims my unmarshalled obj is invalid.
	// recovering from the panic and using my object that already has the json body bound to it.
	var json []Patch

	r := c.Bind(&json)
	if r != nil {
		fmt.Println(r)
	} else {
		if json[0].Op != "replace" && json[0].Path != "/status" {
			c.JSON(http.StatusBadRequest, gin.H{"message": "PATCH support is limited and can only replace the /status path"})
			return
		}
		var taipeiCity TaipeiCity

		if tr.db.First(&taipeiCity, id).RecordNotFound() {
			c.JSON(http.StatusNotFound, gin.H{"message": "not found"})
		} else {
			//taipeiCity.Status = json[0].Value

			tr.db.Save(&taipeiCity)
			c.JSON(http.StatusOK, taipeiCity)
		}
	}
}

func (tr *TaipeiCityResource) DeleteTaipeiCity(c *gin.Context) {
	id, err := tr.getId(c)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem decoding id sent"})
		return
	}

	var taipeiCity TaipeiCity

	if tr.db.First(&taipeiCity, id).RecordNotFound() {
		c.JSON(http.StatusNotFound, gin.H{"message": "not found"})
	} else {
		tr.db.Delete(&taipeiCity)
		c.Data(http.StatusNoContent, "application/json", make([]byte, 0))
	}
}

func (tr *TaipeiCityResource) getId(c *gin.Context) (int32, error) {
	idStr := c.Params.ByName("id")
	id, err := strconv.Atoi(idStr)
	if err != nil {
		log.Print(err)
		return 0, err
	}
	return int32(id), nil
}

/**
* on patching: http://williamdurand.fr/2014/02/14/please-do-not-patch-like-an-idiot/
 *
  * patch specification https://tools.ietf.org/html/rfc5789
   * json definition http://tools.ietf.org/html/rfc6902
*/

type Patch struct {
	Op    string `json:"op" binding:"required"`
	From  string `json:"from"`
	Path  string `json:"path"`
	Value string `json:"value"`
}

